databasename='bigclonebench';
endpoint='localhost';
connector='/home/cat409/Programs/DbVisualizer/jdbc/postgresql/postgresql.jar';
username='cat409';
password='cat409';
opts = configureJDBCDataSource("Vendor","PostgreSQL");
opts = setConnectionOptions(opts                                 ,...
       "DatabaseName",databasename          ,...
       "DataSourceName",databasename        ,...
       "Server", endpoint                   ,...
       "PortNumber", 5432                   ,...
       "JDBCDriverLocation", connector      );
disp(opts)
saveAsJDBCDataSource(opts);
dcon = database(databasename,username,password);