clear;
% load('groundTruth/BCBenchmark.mat', 'clones', 'false_positives','functions');
load('G:/ECCD/ECCD/GroundTruth-BCB/BCBenchmark.mat', 'clones', 'false_positives', 'functions');

%% analyze results in NiCad
recall_nicad=zeros(7,6);
hitNum_nicad=zeros(7,6);
falseAlarmNum_nicad=zeros(7,1);
reportNum_nicad=zeros(7,1);
% path="/home/cat409/Programs/RelatedWork/NiCad-6.2/experiments/BCB-ERA-latest/";
path="G:/ECCD/data/NiCad-6.2/experiments/BCB-ERA-latest/";
% [hit,falseAlarm,reportNum] = analysisNiCad_BCB_CCD(path,"type1",clones,false_positives);
% [recall_nicad(1,:),hitNum_nicad(1,:)] = analysisHit(hit,clones);
% falseAlarmNum_nicad(1,:)=size(falseAlarm,1);
% reportNum_nicad(1,:)=reportNum;
% [hit,falseAlarm,reportNum] = analysisNiCad_BCB_CCD(path,"type2",clones,false_positives);
% [recall_nicad(2,:),hitNum_nicad(2,:)] = analysisHit(hit,clones);
% falseAlarmNum_nicad(2,:)=size(falseAlarm,1);
% reportNum_nicad(2,:)=reportNum;
% [hit,falseAlarm,reportNum] = analysisNiCad_BCB_CCD(path,"type2c",clones,false_positives);
% [recall_nicad(3,:),hitNum_nicad(3,:)] = analysisHit(hit,clones);
% falseAlarmNum_nicad(3,:)=size(falseAlarm,1);
% reportNum_nicad(3,:)=reportNum;
% [hit,falseAlarm,reportNum] = analysisNiCad_BCB_CCD(path,"type3_1",clones,false_positives);
% [recall_nicad(4,:),hitNum_nicad(4,:)] = analysisHit(hit,clones);
% falseAlarmNum_nicad(4,:)=size(falseAlarm,1);
% reportNum_nicad(4,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisNiCad_BCB_CCD(path,"type3_2",clones,false_positives);
[recall_nicad(5,:),hitNum_nicad(5,:)] = analysisHit(hit,clones);
falseAlarmNum_nicad(5,:)=size(falseAlarm,1);
reportNum_nicad(5,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisNiCad_BCB_CCD(path,"type3_2c",clones,false_positives);
[recall_nicad(6,:),hitNum_nicad(6,:)] = analysisHit(hit,clones);
falseAlarmNum_nicad(6,:)=size(falseAlarm,1);
reportNum_nicad(6,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisNiCad_BCB_CCD(path,"all",clones,false_positives);
[recall_nicad(7,:),hitNum_nicad(7,:)] = analysisHit(hit,clones);
falseAlarmNum_nicad(7,:)=size(falseAlarm,1);
reportNum_nicad(7,:)=reportNum;

%% analyze results in SourcererCC
recall_scc=zeros(5,6);
hitNum_scc=zeros(5,6);
falseAlarmNum_scc=zeros(5,1);
reportNum_scc=zeros(5,1);
path="G:/ECCD/data/SourcererCC/experiments/BCB-ERA-latest/";
[hit,falseAlarm,reportNum] = analysisSourcererCC_BCB_CCD(path,0.4,clones,false_positives);
[recall_scc(1,:),hitNum_scc(1,:)] = analysisHit(hit,clones);
falseAlarmNum_scc(1,:)=size(falseAlarm,1);
reportNum_scc(1,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisSourcererCC_BCB_CCD(path,0.5,clones,false_positives);
[recall_scc(2,:),hitNum_scc(2,:)] = analysisHit(hit,clones);
falseAlarmNum_scc(2,:)=size(falseAlarm,1);
reportNum_scc(2,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisSourcererCC_BCB_CCD(path,0.6,clones,false_positives);
[recall_scc(3,:),hitNum_scc(3,:)] = analysisHit(hit,clones);
falseAlarmNum_scc(3,:)=size(falseAlarm,1);
reportNum_scc(3,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisSourcererCC_BCB_CCD(path,0.7,clones,false_positives);
[recall_scc(4,:),hitNum_scc(4,:)] = analysisHit(hit,clones);
falseAlarmNum_scc(4,:)=size(falseAlarm,1);
reportNum_scc(4,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisSourcererCC_BCB_CCD(path,0.8,clones,false_positives);
[recall_scc(5,:),hitNum_scc(5,:)] = analysisHit(hit,clones);
falseAlarmNum_scc(5,:)=size(falseAlarm,1);
reportNum_scc(5,:)=reportNum;

%% analyze results in Deckard
recall_deckard=zeros(2,6);
hitNum_deckard=zeros(2,6);
falseAlarmNum_deckard=zeros(2,1);
reportNum_deckard=zeros(2,1);
path="G:/ECCD/data/Deckard/experiments/BCB-ERA-latest/reports/";
[hit,falseAlarm,reportNum] = analysisDeckard_BCB_CCD(path,0.8,clones,false_positives);
[recall_deckard(1,:),hitNum_deckard(1,:)] = analysisHit(hit,clones);
falseAlarmNum_deckard(1,:)=size(falseAlarm,1);
reportNum_deckard(1,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisDeckard_BCB_CCD(path,0.9,clones,false_positives);
[recall_deckard(2,:),hitNum_deckard(2,:)] = analysisHit(hit,clones);
falseAlarmNum_deckard(2,:)=size(falseAlarm,1);
reportNum_deckard(2,:)=reportNum;

%% analyze results in CloneWorks
recall_cw=zeros(4,6);
hitNum_cw=zeros(4,6);
falseAlarmNum_cw=zeros(4,1);
reportNum_cw=zeros(4,1);
path="G:/ECCD/data/CloneWorks/experiments/results/function-level/BCB-ERA-latest/";
% need 64GB RAM
% [hit,falseAlarm,reportNum] = analysisCloneWorks_BCB_CCD(path,0.5,functions,clones,false_positives);
% [recall_cw(1,:),hitNum_cw(1,:)] = analysisHit(hit,clones);
% falseAlarmNum_cw(1,:)=size(falseAlarm,1);
% reportNum_cw(1,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisCloneWorks_BCB_CCD(path,0.6,functions,clones,false_positives);
[recall_cw(2,:),hitNum_cw(2,:)] = analysisHit(hit,clones);
falseAlarmNum_cw(2,:)=size(falseAlarm,1);
reportNum_cw(2,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisCloneWorks_BCB_CCD(path,0.7,functions,clones,false_positives);
[recall_cw(3,:),hitNum_cw(3,:)] = analysisHit(hit,clones);
falseAlarmNum_cw(3,:)=size(falseAlarm,1);
reportNum_cw(3,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisCloneWorks_BCB_CCD(path,0.8,functions,clones,false_positives);
[recall_cw(4,:),hitNum_cw(4,:)] = analysisHit(hit,clones);
falseAlarmNum_cw(4,:)=size(falseAlarm,1);
reportNum_cw(4,:)=reportNum;

%% analyze results in Oreo
recall_oreo=zeros(6,6);
hitNum_oreo=zeros(6,6);
falseAlarmNum_oreo=zeros(6,1);
reportNum_oreo=zeros(6,1);
path="G:/ECCD/data/Oreo/experiments/BCB-ERA-latest/";
[hit,falseAlarm,reportNum] = analysisOreo_BCB_CCD(path,0.3,functions,clones,false_positives);
[recall_oreo(1,:),hitNum_oreo(1,:)] = analysisHit(hit,clones);
falseAlarmNum_oreo(1,:)=size(falseAlarm,1);
reportNum_oreo(1,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisOreo_BCB_CCD(path,0.4,functions,clones,false_positives);
[recall_oreo(2,:),hitNum_oreo(2,:)] = analysisHit(hit,clones);
falseAlarmNum_oreo(2,:)=size(falseAlarm,1);
reportNum_oreo(2,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisOreo_BCB_CCD(path,0.5,functions,clones,false_positives);
[recall_oreo(3,:),hitNum_oreo(3,:)] = analysisHit(hit,clones);
falseAlarmNum_oreo(3,:)=size(falseAlarm,1);
reportNum_oreo(3,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisOreo_BCB_CCD(path,0.6,functions,clones,false_positives);
[recall_oreo(4,:),hitNum_oreo(4,:)] = analysisHit(hit,clones);
falseAlarmNum_oreo(4,:)=size(falseAlarm,1);
reportNum_oreo(4,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisOreo_BCB_CCD(path,0.7,functions,clones,false_positives);
[recall_oreo(5,:),hitNum_oreo(5,:)] = analysisHit(hit,clones);
falseAlarmNum_oreo(5,:)=size(falseAlarm,1);
reportNum_oreo(5,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisOreo_BCB_CCD(path,0.8,functions,clones,false_positives);
[recall_oreo(6,:),hitNum_oreo(6,:)] = analysisHit(hit,clones);
falseAlarmNum_oreo(6,:)=size(falseAlarm,1);
reportNum_oreo(6,:)=reportNum;

%% analyze results in NIL
recall_NIL=zeros(9,6);
hitNum_NIL=zeros(9,6);
falseAlarmNum_NIL=zeros(9,1);
reportNum_NIL=zeros(9,1);
path="G:/ECCD/data/NIL/experiments/BCB/";
[hit,falseAlarm,reportNum] = analysisNIL_BCB_CCD(path,0.1,functions,clones,false_positives);
[recall_NIL(1,:),hitNum_NIL(1,:)] = analysisHit(hit,clones);
falseAlarmNum_NIL(1,:)=size(falseAlarm,1);
reportNum_NIL(1,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisNIL_BCB_CCD(path,0.2,functions,clones,false_positives);
[recall_NIL(2,:),hitNum_NIL(2,:)] = analysisHit(hit,clones);
falseAlarmNum_NIL(2,:)=size(falseAlarm,1);
reportNum_NIL(2,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisNIL_BCB_CCD(path,0.3,functions,clones,false_positives);
[recall_NIL(3,:),hitNum_NIL(3,:)] = analysisHit(hit,clones);
falseAlarmNum_NIL(3,:)=size(falseAlarm,1);
reportNum_NIL(3,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisNIL_BCB_CCD(path,0.4,functions,clones,false_positives);
[recall_NIL(4,:),hitNum_NIL(4,:)] = analysisHit(hit,clones);
falseAlarmNum_NIL(4,:)=size(falseAlarm,1);
reportNum_NIL(4,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisNIL_BCB_CCD(path,0.5,functions,clones,false_positives);
[recall_NIL(5,:),hitNum_NIL(5,:)] = analysisHit(hit,clones);
falseAlarmNum_NIL(5,:)=size(falseAlarm,1);
reportNum_NIL(5,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisNIL_BCB_CCD(path,0.6,functions,clones,false_positives);
[recall_NIL(6,:),hitNum_NIL(6,:)] = analysisHit(hit,clones);
falseAlarmNum_NIL(6,:)=size(falseAlarm,1);
reportNum_NIL(6,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisNIL_BCB_CCD(path,0.7,functions,clones,false_positives);
[recall_NIL(7,:),hitNum_NIL(7,:)] = analysisHit(hit,clones);
falseAlarmNum_NIL(7,:)=size(falseAlarm,1);
reportNum_NIL(7,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisNIL_BCB_CCD(path,0.8,functions,clones,false_positives);
[recall_NIL(8,:),hitNum_NIL(8,:)] = analysisHit(hit,clones);
falseAlarmNum_NIL(8,:)=size(falseAlarm,1);
reportNum_NIL(8,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisNIL_BCB_CCD(path,0.9,functions,clones,false_positives);
[recall_NIL(9,:),hitNum_NIL(9,:)] = analysisHit(hit,clones);
falseAlarmNum_NIL(9,:)=size(falseAlarm,1);
reportNum_NIL(9,:)=reportNum;

%% analyze results in Siamese
recall_siamese=zeros(4,6);
hitNum_siamese=zeros(4,6);
falseAlarmNum_siamese=zeros(4,1);
reportNum_siamese=zeros(4,1);
% path="/home/cat409/Programs/RelatedWork/Siamese/experiments/BCB-ERA-latest/";
path="G:/ECCD/data/Siamese/experiments/BCB-ERA-latest/"
[hit,falseAlarm,reportNum] = analysisSiamese_BCB_CCD(path+"/sim-0.08/",clones,false_positives);
[recall_siamese(1,:),hitNum_siamese(1,:)] = analysisHit(hit,clones);
falseAlarmNum_siamese(1,:)=size(falseAlarm,1);
reportNum_siamese(1,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisSiamese_BCB_CCD(path+"/sim-0.1/",clones,false_positives);
[recall_siamese(2,:),hitNum_siamese(2,:)] = analysisHit(hit,clones);
falseAlarmNum_siamese(2,:)=size(falseAlarm,1);
reportNum_siamese(2,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisSiamese_BCB_CCD(path+"/sim-0.3/",clones,false_positives);
[recall_siamese(3,:),hitNum_siamese(3,:)] = analysisHit(hit,clones);
falseAlarmNum_siamese(3,:)=size(falseAlarm,1);
reportNum_siamese(3,:)=reportNum;
[hit,falseAlarm,reportNum] = analysisSiamese_BCB_CCD(path+"/sim-0.5/",clones,false_positives);
[recall_siamese(4,:),hitNum_siamese(4,:)] = analysisHit(hit,clones);
falseAlarmNum_siamese(4,:)=size(falseAlarm,1);
reportNum_siamese(4,:)=reportNum;

clear hit reportNum hit_seed reportNum_seed hit falseAlarm reportNum;