load('astens-bwa/BCBenchmark-latest.mat', 'clones', 'false_positives');
idx=table2array(clones(:,4))==1;
T1=[table2array(clones(idx,1:2)) table2array(clones(idx,5:6))];
idx=table2array(clones(:,4))==2;
T2=[table2array(clones(idx,1:2)) table2array(clones(idx,5:6))];
cate=table2array(clones(:,4));
lineSim=table2array(clones(:,5));
tokenSim=table2array(clones(:,6));
syntacticalSim=lineSim;
idx=lineSim>tokenSim;
syntacticalSim(idx,:)=tokenSim(idx,:);
idx=cate==3&syntacticalSim>=0.9;
VST3=[table2array(clones(idx,1:2)) table2array(clones(idx,5:6))];
idx=cate==3&syntacticalSim<0.9&syntacticalSim>=0.7;
ST3=[table2array(clones(idx,1:2)) table2array(clones(idx,5:6))];
idx=cate==3&syntacticalSim<0.7&syntacticalSim>=0.5;
MT3=[table2array(clones(idx,1:2)) table2array(clones(idx,5:6))];
idx=cate==3&syntacticalSim<0.5;
WT3=[table2array(clones(idx,1:2)) table2array(clones(idx,5:6))];
T1=[T1 ones(size(T1,1),1)];
T2=[T2 ones(size(T2,1),1)*2];
VST3=[VST3 ones(size(VST3,1),1)*3];
ST3=[ST3 ones(size(ST3,1),1)*4];
MT3=[MT3 ones(size(MT3,1),1)*5];
WT3=[WT3 ones(size(WT3,1),1)*6];
fa=[table2array(false_positives(:,1:2)) table2array(false_positives(:,5:6))];
fa=[fa zeros(size(fa,1),1)];
pairs=[T1;T2;VST3;ST3;MT3;WT3;fa];
pairs=[pairs(:,1:2) pairs(:,5) pairs(:,3:4)];
writematrix(pairs,'samples-latest.txt','Delimiter',' ');